name: test-262 Runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    ARTIFACT-NAME: "test-262-test-run"

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # NOTE: We can't use git checkout from the runner, so we checkout using this step.
    - name: Checkout test-262 repository
      uses: actions/checkout@v4
      with:
        repository: 'tc39/test262'
        path: './test262'
    - name: Restore dependencies
      run: dotnet restore JSS.Test262Runner/JSS.Test262Runner.csproj
    - name: Build our Test262Runner
      run: dotnet build --no-restore --configuration Release JSS.Test262Runner/JSS.Test262Runner.csproj
    - name: Download previous test run artifact
      uses: dawidd6/action-download-artifact@v3
      with:
          name: ${{ env.ARTIFACT-NAME }}
          if_no_artifact_found: "ignore"
    - name: Setup previous test run for diffing
      run: GCI -filter test-262-run*.txt | Rename-Item -newname "from-test-262-run.txt"
    - name: Start our Test262Runner
      run: dotnet run --no-build --configuration Release --project JSS.Test262Runner/JSS.Test262Runner.csproj -- -q
    - name: Upload test run artifact
      uses: actions/upload-artifact@v4
      with:
          name: ${{ env.ARTIFACT-NAME }}
          path: test-262-run-*.txt
    - name: Setup current test run for diffing
      run: GCI -filter "test-262-run*.txt" | Rename-Item -newname "to-test-262-run.txt"
    - name: Perform test-262 test run diffing
      run: dotnet run --no-build --configuration Release --project JSS.Test262Runner/JSS.Test262Runner.csproj -- diff -f from-test-262-run.txt -t to-test-262-run.txt
